contacts/urls.py
from django.conf.urls import patterns, url

from contacts import views

urlpatterns = patterns(
    '',
    url(r'^services/$', views.index, name='contacts_index'),
    url(r'^(?P<contact_id>\d+)/$', views.viewContact, name='contact_detail'),
    url(r'^service/$', views.viewServices, name='contact_services'),
    url(r'^service/(?P<service_id>\d+)/$', views.viewService, name='contact_service_detail'),
    url(r'^search/$', views.searchContact, name='contact_search'),
)

enmashcorp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from enmashcorp import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_action, name='login'),
    url(r'^logout/$', views.logout_action, name='logout'),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^filestorage/', include('filestorage.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

filestorage/urls.py
from django.conf.urls import patterns, url

from filestorage import views

urlpatterns = patterns(
    '',
    url(r'^', views.index, name='filestorage_index'),
)

news/urls.py
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns(
    '',
    url(r'^list/$', views.index, name="news_index"),
)

contacts/models.py
from django.db import models
from django.contrib import admin

class ContactService(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название службы')

    def __str__(self):
        return self.name

class PersonContact(models.Model):
    name = models.CharField(max_length=200, verbose_name='Имя контакта')
    interofficePhone = models.CharField(max_length=100, null=True, blank=True, verbose_name='Внутренний телефон')
    landlinePhone = models.CharField(max_length=100, null=True, blank=True, verbose_name='Внешний телефон')
    service = models.ForeignKey(ContactService)

    class Meta:
        permissions = (
            ("view_contact", "Can view a contact"),
        )

    def __str__(self):
        return self.name

filestorage/models.py
from os import sysconf
import os
from django.db import models
from django.contrib import admin
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from enmashcorp.settings import MEDIA_URL


class UploadedFile(models.Model):
    name = models.CharField(max_length=200)
    createdAt = models.DateTimeField(auto_created=True)
    file = models.FileField(upload_to='filestorage', max_length=500)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.pk is not None:
            originalFile = UploadedFile.objects.get(pk=self.pk)
            if originalFile.file != self.file:
                originalFile.file.delete(False)
        super(UploadedFile, self).save(*args, **kwargs)



@receiver(pre_delete, sender=UploadedFile)
def uploaded_file_pre_delete(sender, instance, **kwargs):
    instance.file.delete(False)


admin.site.register(UploadedFile)

news/models.py
from django.db import models

# Create your models here.

class NewsItem(models.Model):
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_created=True)
    text = models.TextField()
    publish = models.BooleanField(default=False)

    def __str__(self):
        return self.title

filestorage/forms.py
from django import forms


class SearchForm(forms.Form):
    searchQuery = forms.CharField(
        label='Строка поиска',
        max_length=10,
        min_length=3,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Что ищем?'
            }
        )
    )

contacts/views.py
from django.core.urlresolvers import reverse_lazy, reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

# Create your views here.
from contacts.models import PersonContact, ContactService


def index(request):

    # if request.user.has_perm('contacts.view_contact'):
    #     print('yey')
    # else:
    #     print('nope')

    services = ContactService.objects.all()
    return render(
        request,
        'contacts/index.html',
        {
            'services': services
        })


def viewServices(request):
    return HttpResponse("Services page")


def viewContact(request, contact_id):

    if request.user.has_perm('contacts.view_contact'):
        contact = get_object_or_404(PersonContact, pk=contact_id)

        return render(
            request,
            'contacts/showContact.html',
            {
                'contact': contact
            }
        )
    else:
        return HttpResponseRedirect(
            reverse('index')
        )




def viewService(request, service_id):
    service = get_object_or_404(ContactService, pk=service_id)

    return render(
        request,
        'contacts/showService.html',
        {
            'service': service
        }
    )


def searchContact(request):
    query = request.POST['contact_search_query']
    contacts = PersonContact.objects.filter(
        name__icontains=query
    )
    return render(
        request,
        'contacts/search_result.html',
        {
            'contacts': contacts
        }
    )

enmashcorp/views.py
from django.contrib import auth
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render

# @login_required(login_url='/login/')
from news.models import NewsItem


def index(request):

    news = NewsItem.objects.filter(publish=True).order_by('-created_at')[0:5]

    return render(
        request,
        'enmashcorp/index.html',
        {
            'news': news
        }
    )


def login_action(request):

    if request.method == 'POST':
        user = auth.authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user is not None:
            login(request, user)
            login(request, user)
            return HttpResponseRedirect(
                reverse('index')
            )

    return render(
        request,
        'enmashcorp/login.html'
    )


def logout_action(request):
    logout(request)
    return HttpResponseRedirect(
        reverse('index')
    )

filestorage/views.py
import os
from django.shortcuts import render

# Create your views here.
from django.template.context import RequestContext
from enmashcorp.settings import STATICFILES_DIRS, BASE_DIR, MEDIA_ROOT, MEDIA_URL
from filestorage.forms import SearchForm
from filestorage.models import UploadedFile


def index(request):
    files = None
    if request.method == 'POST':
        searchForm = SearchForm(request.POST)
        if searchForm.is_valid():
            files = UploadedFile.objects.filter(
                name__icontains=searchForm.cleaned_data['searchQuery']
            )
    else:
        searchForm = SearchForm

    if files is None:
        files = UploadedFile.objects.all()

    return render(
        request,
        'filestorage/index.html',
        {
            'files': files,
            'search_form': searchForm,
            'request': request
        }
    )

news/views.py
from django.shortcuts import render
from news.models import NewsItem


def index(request):

    news = NewsItem.objects.filter(publish = True).order_by('-created_at')

    return render(
        request,
        'news/index.html',
        {
            'news': news
        }
    )

contacts/templates/contacts/index.html
{% extends 'enmashcorp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-9">
        <h1>Контакты</h1>
        {% block contacts_content %}
        <h2>Список служб</h2>
        <div class="list-group">
            {% for service in services %}
                <a class="list-group-item" href="{% url 'contact_service_detail' service.id %}">
                    {{ service.name }}
                    <span class="pull-right label label-info">Контактов в службе: {{ service.personcontact_set.all | length }}</span>
                </a>
            {% endfor %}
        </div>
        {% endblock %}
    </div>
    <div class="col-xs-12 col-sm-3">
        <h2>Поиск</h2>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'contact_search' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" name="contact_search_query" placeholder="Поиск контактов">
            </div>
            <div class="form-group">
                <button class="btn btn-primary pull-right" type="submit">Искать</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

contacts/templates/contacts/search_result.html
{% extends 'contacts/index.html' %}

{% block contacts_content %}
<h2>Результаты поиска</h2>
{% if contacts %}
    <div class="alert alert-success alert-dismissable">
        <p>Найдено результатов: {{ contacts | length }}</p>
    </div>
    <div class="list-group">
    {% for contact in contacts %}
        <a class="list-group-item" href="{% url 'contact_detail' contact.id %}">
            {{ contact.name }}
            <span class="label label-info pull-right">{{ contact.service.name }}</span>
        </a>
    {% endfor %}
    </div>
{% else %}
    <div class="alert alert-danger" role="alert">
        <p>Поиск не дал результатов</p>
    </div>
{% endif %}
{% endblock %}

contacts/templates/contacts/showContact.html
{% extends 'contacts/index.html' %}

{% block contacts_content %}
<h2>{{ contact.service.name }}</h2>
<a href="{% url 'contact_service_detail' contact.service.id %}">Все сотрудники службы</a>
<h3>{{ contact.name }}</h3>
<ul>
    <li>Городской телефон: {{ contact.landlinePhone }}</li>
    <li>Внутренний телефон: {{ contact.interofficePhone }}</li>
</ul>
{% endblock %}

contacts/templates/contacts/showService.html
{% extends 'contacts/index.html' %}

{% block contacts_content %}
<h2>Служба - {{ service.name }}</h2>
<div class="list-group">
    {% for contact in service.personcontact_set.all %}
            <a href="{% url 'contact_detail' contact.id %}" class="list-group-item">
                {{ contact.name }}
                {% if contact.landlinePhone or contact.interofficePhone %}
                <span class="label label-success pull-right">
                    {% if contact.landlinePhone %}
                        {{ contact.landlinePhone }}
                    {% endif %}
                    {% if contact.landlinePhone and contact.interofficePhone %}
                        |
                    {% endif %}
                    {% if contact.interofficePhone %}
                        {{ contact.interofficePhone }}
                    {% endif %}
                </span>
                {% endif %}
            </a>

    {% endfor %}
</div>
{% endblock %}

filestorage/templates/filestorage/index.html
{% extends 'enmashcorp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-8">
        <h1>Каталог Файлов</h1>

        {% if request.method == 'POST' %}
            {% if files %}
            <div class="alert alert-success" role="alert">
                Найдено файлов: {{ files | length }}
            </div>
            {% else %}
            <div class="alert alert-danger" role="alert">
                Найдено файлов: {{ files | length }}
            </div>
            {% endif %}
        {% endif %}

        <ul class="list-group">
            {% for file in files %}
            <li class="list-group-item">
                <span class="badge">{{ file.createdAt | date:"d/M/Y"}}</span>
                <a href="{{ STATIC_URL}}{{ file.file }}">{{ file.name }}</a>
            </li>
            {% endfor %}
        </ul>


    </div>
    <div class="col-xs-12 col-sm-4">
        <h2>Поиск файлов</h2>
        <form action="{% url 'filestorage_index' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ search_form.searchQuery }}
            </div>
            <button type="submit" class="btn btn-primary">Искать</button>
        </form>
    </div>
</div>
{% endblock %}

news/templates/news/block/news-list-item.html
<h3>
    {{ newsItem }}
    <small><span class="label label-success pull-right">{{ newsItem.created_at }}</span></small>
</h3>
<p>{{ newsItem.text }}</p>
<hr>

news/templates/news/index.html
{% extends 'enmashcorp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <h1>Новости</h1>
{% if news %}
    <div class="list-group">
    {% for newsItem in news %}
        <div class="list-group-item">
            {% include 'news/block/news-list-item.html' %}
        </div>
    {% endfor %}
    </div>
{% endif %}
    </div>
</div>

{% endblock %}

templates/enmashcorp/base.html
<!DOCTYPE html>
<html>
<head lang="en">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}

    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/dist/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    {% endblock %}

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block header_nav %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'images/logo.png' %}">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="main-menu">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'news_index' %}">Новости</a></li>
                <li><a href="{% url 'contacts_index' %}">Контакты</a></li>
                <li><a href="{% url 'filestorage_index' %}">Файлы</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="#">Добрый день, {{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}">Выход</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content_no_container %}
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'vendor/jquery/dist/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/dist/js/bootstrap.js' %}"></script>
{% endblock %}
</body>
</html>

templates/enmashcorp/block/news-block.html
<h2>Новости</h2>
<div class="list-group">
    {% for newsItem in news %}
    <div class="list-group-item">
        {% include 'news/block/news-list-item.html' %}
    </div>
    {% endfor %}
</div>

templates/enmashcorp/index.html
{% extends 'enmashcorp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-6">
        {% if news %}
        {% include 'enmashcorp/block/news-block.html' %}
        {% endif %}
    </div>
</div>
{% endblock %}

templates/enmashcorp/login.html
{% extends 'enmashcorp/base.html' %}

{% block content %}
<form class="form-signin" method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    <h2>Вход</h2>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Имя" name="username" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Пароль" name="password" required>
    </div>
    <div class="form-group">
        <button type="submit" class="btn-primary btn">Вход</button>
    </div>
</form>
{% endblock %}